Note-Vault/Note-Vault

.github/ISSUE_TEMPLATE/bug.yml

fixes #2 , kindly review and merge

fix: linting error in bug.yml

---

README.md

added the correct deployment link and preview images
fixes issues #11 and #21

Update documentation: fixes issues #11 and #21

---

views/note.ejs
views/partials/header.ejs

I have changed the UI of Saved notes using TailwindCSS and adding font awesome icons

Improving notes UI

---

CONTRIBUTING.md
package.json

Added CONTRIBUTING.md file under #31 assigned to me

added contributing.md file

---

views/home.ejs

issue #33 solved
Anchor tag styling added

Anchor tag styling

---

server.js
views/note.ejs
views/search.ejs

Solved issue No. #54 under GSSOC'24.
Implemented a feature to include dates in notes, enhancing organization and clarity for users. This addition facilitates better time management and reference within the note-taking system.

Added Creation date in note

---

views/search.ejs

Updated the UI of the search result page by adding a navbar to the page for easier navigation for the user between pages or logout directly from the page 
Solving issue #63

Update search.ejs 

---

package-lock.json
server.js
views/404.ejs

Added Custom error handler for 404 not found.

page not found route added

---

package-lock.json
package.json
public/style/style.css
views/home.ejs

I have changed the font-style and size of the font to look modern.

font changed

---

package-lock.json
package.json
public/style/style.css
views/home.ejs

Reverts Note-Vault/Note-Vault#98

Revert "font changed"

---

views/home.ejs

Updated UI for better user experience. Following is the result -->

Update home.ejs  Issue#32

---

views/home.ejs

Reverts Note-Vault/Note-Vault#107
Take the latest pull then apply your changes there is old code in your codebase .. changes must be in the latest code

Revert "Update home.ejs  Issue#32"

---

views/register.ejs

**Issue #104 Fixed**
**Restriction added in name field**
It should took only letters any other number and special character now allowed.
**Screen shot**

Fixed : Restriction added in name field

---

views/partials/header.ejs
views/register.ejs

**Issue #105 Fixed**
Extra space removed in login and signup page.
**Screenshot**
Before 
After

Fixed : Space removed in signup and login page

---

public/script/script.js
public/style/style.css
views/home.ejs
views/login.ejs
views/note.ejs
views/register.ejs
views/search.ejs
views/success.ejs

Reverts Note-Vault/Note-Vault#128

Revert "Fix: issue/113 Toggle-mode overlapping."

---

views/login.ejs
views/register.ejs

As per discussed in issue #95 , I have made the Login and Register button on login and register pages clickable in the entire region. 
Issue was of overlying container divs.
Please review.
The signup page looks like this right now:

Login button now clickable

---

public/style/style.css
views/home.ejs

transition in why choose NoteVault is added
issue no #117
https://github.com/Note-Vault/Note-Vault/assets/149225785/cfc1c021-0010-4af5-a85d-43e238943871
https://github.com/Note-Vault/Note-Vault/assets/149225785/e0d1ff70-2d2f-492b-9c1a-7be947c3680c
@VaibhavArora314   Please don't forget to add label and assign this PR to me

why choose notevault

---

public/style/style.css

Fixed Alignment of sun and moon in Change Mode Section .
issue number #155
Before 
After

Dark mode and Light mode icon is not well aligned  #155

---

public/style/style.css
views/home.ejs

Reverts Note-Vault/Note-Vault#148

Revert "Changed the cards title and view"

---

public/style/style.css
views/login.ejs

icons added to login page

---

public/style/style.css
views/login.ejs

Reverts Note-Vault/Note-Vault#167

Revert "icons added to login page"

---

views/home.ejs

I have added the logo beside the title in navbar.

logo added beside title

---

public/style/style.css
views/register.ejs

I have added icons to input fields in register page.

icons added to register page

---

public/style/style.css
views/home.ejs

closes: #173
I have added text  flip effect have a look on it

Added some animation to text in home page 

---

public/style/style.css
views/home.ejs

I have made the changes keeping in view of the color theme used in the web page

Enhancement of text color and font in the card's text

---

package-lock.json
public/style/style.css

Hey, I have Fixed issue #176 
Please take a look and review it.

Styled "Scroll to top Btn and Vertical Scrollbar" Matching to websites design theme.

---

package-lock.json
package.json
public/style/style.css
views/home.ejs

I have added hover effects in the navbar section
https://github.com/Note-Vault/Note-Vault/assets/143275265/9cb09ef4-c452-482d-9ebc-c7294f61add9

hover effects added

---

CODE_OF_CONDUCT.md

**fixes#84**
**description:**
- This pull request introduces a Code of Conduct file to establish guidelines for behavior and interaction within the project's /repo's community.
-It consists of all the existing sections that has been corrected. A section of SPECIFIC GUIDELINES (that tells what the community strictly wants ) is added into it.
-By following this Code of Conduct, we will be able to maintain the values of diversity, integrity, and mutual respect.

CODE-OF-CONDUCT.md

---

package-lock.json
package.json
public/style/style.css
views/home.ejs

Fixed the navbar to stay on top of the page.

Fixed navbar on top of the page

---

package-lock.json
package.json
public/style/style.css
views/home.ejs

Reverts Note-Vault/Note-Vault#196

Revert "Fixed navbar on top of the page"

---

public/style/style.css
views/home.ejs

I have updated About Section. The changes made are listed below:
1. Changed the font according to the website.
2. Made the about section responsive.
3. Added Dark mode.
4. Also reduced the content & made sweet and short to read.
DESKTOP VIEW
MOBILE VIEW
Have a look on the changes made and let me know.
Issue:- #190

Updated UI of About Us Section

---

views/home.ejs

Reverts Note-Vault/Note-Vault#202

Revert "The color of the background changed in home.ejs"

---

public/style/style.css

I have updated dark mode in about section. Have a look and let me know.
Please accept my issue & PR under GSSoC'24.
Issue: #214

Updated dark mode in About Section

---

views/note.ejs

i have styled the NOTE page navbar 
before
after
@VaibhavArora314 @goyalh4164 @Ultimateutkarsh11  please review my work

Update Note navbar

---

package-lock.json
package.json
public/style/style.css
views/home.ejs

Should work now, the class name wasn't updated in the home file.

Navbar fixed position on top.

---

public/style/style.css
views/home.ejs

Reverts Note-Vault/Note-Vault#204

Revert "Navbar fixed position on top."

---

.github/workflows/autocomment-pr-raise.yml

Fixes #194 
@VaibhavArora314 please review my PR and merge it if it is good to go

Created autocomment-pr-raise.yml

---

package-lock.json
package.json
public/style/style.css
views/home.ejs
views/partials/header.ejs

Improved the UI of Home Page for the website

Improved UI

---

package-lock.json
package.json
public/style/style.css

Successfully Added Stroke Hover Animations to the Nav Links

Added Animation to the nav links

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Updated pull_request_template.md

---

controllers/notebook.js
model/Notebook.js
public/style/style.css
views/note.ejs
views/partials/header.ejs
views/search.ejs

Added google fonts.
Added creation and finish date
Modified database to store finish date and added timestamps.
Modified design of cards.

Updated card design and added creation and finish date.#187

---

controllers/notebook.js
model/Notebook.js
public/style/style.css
views/note.ejs
views/partials/header.ejs
views/search.ejs

Reverts Note-Vault/Note-Vault#233

Revert "Updated card design and added creation and finish date.#187"

---

views/home.ejs

these icons beautify the page
before
after

Added new icons in Navbar links

---

public/style/style.css
views/home.ejs

issue no #249
The margin and padding was not properly aligned
I have given good look to the page and also added icons
https://github.com/Note-Vault/Note-Vault/assets/137484958/5d7ec3e3-5ade-47ad-b56c-4c7cdf25e6c2

Changed the look of front Page

---

README.md

I added details about how to connect to MongoDB database:
It is related to issue #60

Update README.md to connect to mongoDB database

---

public/style/style.css
views/home.ejs

I have added about link in navbar.
https://github.com/Note-Vault/Note-Vault/assets/143276011/c63d4970-4580-4881-8053-fa34086a1472

about link added 

---

public/style/style.css
views/login.ejs
views/register.ejs

I have added the hide functionality in login page.

hide functionality added in login page

---

public/style/style.css
views/home.ejs
views/partials/footer.ejs

added a footer by updating a footer.ejs   
Also fixed styling issue of the text above the footer 
Created a new pull request to fix the conflict changes check  #232

Added Footer & fixed styling issues

---

.env.example
controllers/user.js
middleware/isAuthenticated.js
middleware/isAuthenticatedlogin.js
server.js
views/addNote.ejs
views/note.ejs
views/search.ejs

Reverts Note-Vault/Note-Vault#262

Revert "Card design update -   #222"

---

routes/staticRoutes.js
views/faqs.ejs
views/home.ejs

@Note-Vault
- i added `/faqs` in static route so we can check output
- it look like this
i just added dummy question of note management 
please check this and merge it

[Feature] : Faqs Page Added

---

public/script/script.js
views/note.ejs

This pr fixes #252.
The demonstration:
https://github.com/Note-Vault/Note-Vault/assets/139672976/654ddbea-e6d3-4c10-a72c-0bd4cebac010

Ask confirmation before delete a note

---

package-lock.json
views/login.ejs
views/register.ejs

I have added email validation for this issue #275  . Please consider this.

added email validation

---

controllers/password.js
middleware/isAuthenticated.js
middleware/isAuthenticatedlogin.js
package-lock.json
package.json
public/style/style.css
routes/password.js
server.js
views/forgot-password.ejs
views/login.ejs
views/reset-password.ejs
views/success.ejs

Forget password implemented
Feat: ADDING FORGET PASSWORD FEATURE #260
NEW FEATURE ADDED
MAIL=your mail(dont use gmail as it has strong security against less secure apps )
PASS=your password
add these feilds in .env reset link emails will be sent via this mail address
- [ N] Breaking change: This change introduces breaking modifications.
- [ Y] Non-breaking change: This change does not introduce breaking modifications.
- [ N] Disrupts existing functionality: This change disrupts the functionality of existing features.
- [ Y] Does not disrupt existing functionality: This change does not disrupt the functionality of existing features.
https://github.com/Note-Vault/Note-Vault/assets/136808696/4f8fa569-af8e-4b3b-8531-2e48905fc5f1

Forget password

---

package-lock.json
public/style/style.css
views/success.ejs

BUG: OVERLAPS POST REGISTERING ACCOUNT #261 resolved.
"Fixes #261 "
all text overflows resolved and light border against dark theme added
- [N] Breaking change: This change introduces breaking modifications.
- [Y] Non-breaking change: This change does not introduce breaking modifications.
- [N] Disrupts existing functionality: This change disrupts the functionality of existing features.
- [Y] Does not disrupt existing functionality: This change does not disrupt the functionality of existing features.
[[Include any relevant screenshots to visually demonstrate the changes made.]](https://github.com/Note-Vault/Note-Vault/assets/136808696/8b499c8c-c4a0-4c5c-bcb7-458342b45550)

BUG: OVERLAPS POST REGISTERING ACCOUNT #261 resolved

---

package-lock.json
package.json
public/style/style.css

Hello Vaibhav,
I have successfully corrected the placement of the mode change button. Now it looks better and is also responsive according to the screen size.
For large screen:-
For small screen:-

Mode Button Position Corrected

---

public/style/style.css
views/home.ejs

Here I have Fix Navbar Alignment in one raw and it is also work in small size.
For Big Screen :
For Small Screen :

Navbar Align In One Raw

---

package-lock.json
views/partials/header.ejs

issue #290 
Added logo in the tab

added logo in the tab issue #290 

---

views/home.ejs

Fixed issue: #348
before
after

Fixed the why Note-Vault Page

---

views/register.ejs

Issue no. #74 resolved.
Now if anyone enter temporary or disposable email for registration it will alert that email is disposable and do not proceed.

email filter added

---

package-lock.json
package.json
routes/user.js
validation/validation.schema.js
validation/zodschema.js

@goyalh4164 @Ultimateutkarsh11  #315 Solved
Thankyou for assigning this issue to me .
I have Added all the validations to the project within the Validation Folder Please Review it ones.
Some of the Proofs of the Endpoints Working  Properly after adding the Validation to the Project.
- **For the Incorrect Email**
- **For the length of the password**
- **For the invalid Email**
- **For the invalid Username**
Looking  For the  without Review Merge if Possible ( eager to get Batch )
Please merge as soon as possible.
Thankyou .

Added Zod Validation To the Project 

---

package-lock.json
server.js
views/home.ejs

I have changed the ui of carousel
Close this under GSSOC'24

Fixed the carousel section ui

---

public/style/style.css
views/home.ejs

Fixed the hero section color to be more attractive.
issue #310 
Navbar at top to be used from anywhere and enhance the user experience.

fixed hero section and Navbar

---

views/home.ejs

Solved Issue #371 Now the footer Quick Links are active
https://github.com/Note-Vault/Note-Vault/assets/154724111/32b14928-a3a3-41c9-9719-c6047f2796fb

Added links to the footer section

---

controllers/password.js
package-lock.json
public/script/script.js
public/style/style.css
views/home.ejs

close #317 
making an Page Responsive

Fix #317 : Make an home page responsive

---

views/register.ejs

fixes issue no.#338
In Sign Up page the icon visibility was not clear I  have fixed that

icon visibility fixed In Sign Up page

---

package-lock.json
views/home.ejs

Hello PA @goyalh4164 
Issue resolved- #335

Fixed heading

---

README.md

Added the git pull command 
resolves #359

Added git pull command in readme file

---

README.md
views/home.ejs

Enhanced UI of About NoteVault section

---

views/faqs.ejs
views/home.ejs

fixed issue: #379 
before
after
https://github.com/Note-Vault/Note-Vault/assets/137484958/9fd553f1-5a4c-4f01-a57e-63527ea2849c

Added testimonials Photos

---

public/style/style.css
views/home.ejs

added instagram and discord logos and links in every part of testimonials section and at footer in follow us section

icon done #422

---

views/home.ejs

Solved Issue #386 
https://github.com/Note-Vault/Note-Vault/assets/154724111/332c22c6-ea8e-420a-8389-8ef3b5ab6c3e

Resolved the navbar link

---

package-lock.json
routes/staticRoutes.js
views/home.ejs
views/pricing.ejs

Fixes #256 
The following changes have been made to the project:
- A "Go Pro!" button has been added to the header. Clicking this button will redirect users to the "/pro" website.
- A dedicated page has been created specifically for this purpose. This page is also responsive, meaning it will display well on all devices. You can find a reference video attached for your convenience.
https://github.com/Note-Vault/Note-Vault/assets/153659573/de6417f8-6e2d-45e2-bf19-6f341a4a1411
**REQUEST:**  I request you to kindly upgrade this issue to a required level as you can see in the attached video, it was not a level 1 issue.
Also, please label the PR and add my name in the assignees section before merging this PR.
Thank You!

Fixes #256 : Added Premium Features

---

controllers/user.js
controllers/verifyEmail.js
model/User.js
package-lock.json
routes/user.js
views/verfiy.ejs

Email Verification Added. After User register he/she will get OTP and have to verify using this OTP to access the application.

Added Email Verification

---

package-lock.json
views/home.ejs

issue no #388
Here I added Scroll to Top button.
I use html , css and js for creating button.
**I expect to provide me level2 if it is possible**

Scrolltotop Button Added

---

package-lock.json
views/home.ejs

Added Hover effect to the whyus section
Before I was not having any hover effect. Now it is added which will give the user a good experience while using this product.
- Closes #364 
https://github.com/Note-Vault/Note-Vault/assets/130668745/d5ec3740-b1a7-48b4-8468-de57d68230e4
If anything needs to be changed, let me know.
Add relevant labels before merging it. Thank you.

hover effect added for whyus section

---

views/home.ejs

Added copyrights section at footer also linked a link where Note-Vault is present. It will get us to the project.
- Closes #432 
Kindly add relevant labels into this.

added copyrights section at footer

---

package-lock.json
package.json
tailwind.config.js
views/faqs.ejs
views/home.ejs

fixed issue: #380 
before
after
https://github.com/Note-Vault/Note-Vault/assets/137484958/44580f6f-7c84-4b04-83ff-6c01ab9d0a57

Styled The FAQ's Page

---

README.md
sample.env

Added how to setup the env file for connection to mongoDB and nodemailer configuration
fixes #435

Updated Readme file, Added sample.env

---

views/home.ejs

#430 added
I have added back to top button which hovers and is consistent with the theme of the website. The button appears when the window size is greater than 100.
https://github.com/Note-Vault/Note-Vault/assets/130165687/7a301340-fad2-4fb4-b273-a11a5801b700
Please review my pr

Added back to top button

---

.hintrc
package-lock.json
public/style/style.css
views/home.ejs

This pull request Fix the navbar with the proper color. Also adjust the register link and sidebar .Set proper container text with the alignment and img in the center.
https://github.com/Note-Vault/Note-Vault/assets/144674061/09b94d33-a97c-4be7-90e1-6732603d9938

Proper alignment of navbar with the color and hover effect
